### PR TITLE
define the start revision of 'Watch' request in WatchTree. Closes #15

### LINKED ISSUE #15: WatchTree missed events
I have an issue with WatchTree in etcd v3. It looks like WatchTree misses some updates and I want to confirm that. I'm not an etcd expert so I might not understand it correctly.

Right now the algorithm looks like that:
```
WatchTree:
  1. list all values
  2. push values to channel
  3. start watching entry
  4. push new values to channel
```

If a value was added between listing all values and starting watching it's missed. Shouldn't `Watch` https://github.com/abronan/libkv/blob/master/store/etcd/v3/etcd.go#L256 be called with specified revision number?

### PR DESCRIPTION
**Pull request by mthenw**
Feel free to change that code :)

### CODE REVIEW

**Comment by abronan** [comment]
Thanks! Although this seems to work more consistently, I can still trigger the race somehow (takes about 10/15 iterations). I'll take a look at it later and investigate further.

**Comment by mthenw** [comment]
Oh, that's interesting. Are you using the same code from the issue?

**Comment by abronan** [comment]
Yes same code from your example.

**Comment by mthenw** [comment]
OK, so I will also investigate more and let you know.

**Comment by mthenw** [comment]
Hmm, I wasn't able to repro that. I curious your findings!

**Comment by abronan** [comment]
When I print the revision that we give to the `WatchTree` call and run your program in a loop, it seems that we're consistently being **7** revisions ahead to the last revision after each run (we're doing 7 operations in total, this makes sense).

There are just times where I found out the gap to be **8** thus **1 revision ahead** and the notification is eaten the same way as before. Unsure why we're being one revision ahead in this case, just some quick findings from debugging.

**Comment by abronan** [comment]
I think it all boils down to the fact that we are doing operations in goroutines: The call to `WatchTree` launches the watch routine and returns immediately, thus racing with the put on `foo/four` that we run in our own goroutine.

If the put on `foo/four` happens just before the call to `List` in `WatchTree`: the `foo/four` we get from the `List` call is thus one revision ahead. When looping over pairs to find the latest modified index, we get that index and give it to `WatchTree` which assumes the event has passed.

So I think a possible solution would be to just move the `List` call outside of the goroutine in `WatchTree` 😅 and thus give a correct index.

So just a very minor modification to your patch :)

**Comment by mthenw** [comment]
OK that make sense! I will update my PR.

**Comment by abronan** [comment]
Awesome! Thanks :)

**Pull request merged**
