### PR TITLE
Add readoptions

### PR DESCRIPTION
**Pull request by zyclonite**
merged the PR adding readOptions

flag consistency works for consul and etcd

### CODE REVIEW

**Comment by abronan** [comment]
@zyclonite Sorry for the very long latency to get back to this PR. Would you mind rebasing your changes on top of the master branch?

Only thing is that it now includes etcd v3 which uses the `etcd.WithSerializable()` flag to set consistency on **Get** and **List** calls. Simple solution would be to call either the normal `Get` or the consistent `Get` with the `etcd.WithSerializable()` option depending on whether the libkv `Consistent` option is set to `true` or `false`. Knowing that the consistent `Get` is the one we call by default.

Let me know if you have time to do this otherwise I will kindly carry to another PR (while keeping your contribution intact).

Thanks!

**Comment by zyclonite** [comment]
should merge again :)
but i had only time to implement the api for v3 ...

**Comment by abronan** [comment]
@zyclonite Woops, I think there was some issue with the rebase. You could either try to fix and force push to your branch, or if this is more convenient for you, feel free to close and open a new PR.

**Comment by zyclonite** [comment]
i'll try a new one, maybe that's easier

**Pull request closed without merging**
